### ISSUE TITLE
Output shows too much 

### ISSUE THREAD

**Issue by frankgerhardt** [magmax/livedoc#1]
I tried the examples. This one shows as the output a55. I would expect that it only shows 5. 

![livedoc-bug](https://cloud.githubusercontent.com/assets/550621/16001457/623d7f34-3152-11e6-9cf3-8a8b1a35e699.png)

In the inspector I see that your intention is to show the expression and a separator. Well, for me that is not my expectation. I just want to see the value. 

In your tests I saw, that your actually want this output. 

```python
    def test_xml(self):
        sut = Print('isinstance(1, int)')
        sut.evaluate({}, {})
        xml = etree.tostring(sut.xml).decode()
        assert xml == (
            '<span class="print">'
            '<span class="print-expression">isinstance(1, int)</span>'
            '<span class="print-sep">True</span>'
            '<span class="print-result">True</span>'
            '</span>'
        )
```

I think the expression and the sep should be empty.

**Comment by frankgerhardt** [comment]
By the way, how can I run the tests?

**Comment by frankgerhardt** [comment]
Now I looked at the other two example documents. in document_2.md 

```markdown
This is just an [example](- "a=TEXT") to show how [ ](- "OUT=a") is equal to [example](- "a == TEXT").
```

I get the output 

```
This is just an example to show how aexampleexample is equal to The expression: `TEXT == a` returned name 'example' is not defined.
```

Same problem. Also in document_1.html.

**Comment by frankgerhardt** [comment]
And then the == check does not work. Because 'example' is not defined. Ofcourse that is not defined. It's the TEXT not a variable.

**Comment by frankgerhardt** [comment]
OUT should also be rendered with some color so that it's easy to recognize.

**Comment by magmax** [comment]
Hello!

Thanks for testing livedoc. It is in an early stage, but I hope you like it.

The real problem here is that the CSS should hide the values you say, and it should be another css (custom.css) that allows anyone to choose the style for everything.

I will work on it as soon as I can, maybe this week.

And I will hide the original value by default.

**Comment by magmax** [comment]
To run tests, you should just run `python setup.py test`. If it doesn't work, just tell me.

**Comment by frankgerhardt** [comment]
I tried that already. 

```
$ python setup.py test
running test
running egg_info
writing entry points to livedoc.egg-info/entry_points.txt
writing top-level names to livedoc.egg-info/top_level.txt
writing requirements to livedoc.egg-info/requires.txt
writing livedoc.egg-info/PKG-INFO
writing dependency_links to livedoc.egg-info/dependency_links.txt
writing pbr to livedoc.egg-info/pbr.json
reading manifest file 'livedoc.egg-info/SOURCES.txt'
writing manifest file 'livedoc.egg-info/SOURCES.txt'
running build_ext
usage: setup.py [options] [file_or_dir] [file_or_dir] [...]
setup.py: error: unrecognized arguments: --cov-report=term-missing --cov --cov-report=term-missing
  inifile: /home/user/git/livedoc/setup.cfg
  rootdir: /home/user/git/livedoc
```

Something with the coverage report is wrong.

**Comment by magmax** [comment]
I usually have some problems with pytest-cov package.

You can do the same than the `.travis.yml` file:

1.  Create a virtual environment to avoid to modify anything. Example: `virtualenv venv`
2.  Enter in the virtual environment. Probably you already know how: `. venv/bin/activate`
3.  Install test dependencies manually: `pip install -U flake8 pytest pytest-cov`
4.  Install the library in development mode: `python setup.py develop`
5.  Run the tests: `py.test`

**Comment by frankgerhardt** [comment]
Ok, running the tests works now.

**Comment by magmax** [comment]
It should be solved in version 0.3.2.

I've already tested everything with integers, but failed with strings. Fixed the autotype method.

**Comment by frankgerhardt** [comment]
Also the output is now generated correctly. 

I'd suggest to use red only for errors and show other results in green, blue etc. but not red.

**Comment by frankgerhardt** [comment]
Oops, no, in document_2.md I get the following error that the name 'example' is not defined. Sure, example is not a name. Looks more like the error message is wrong. 
```
The expression: `a == TEXT` returned name 'example' is not defined
Traceback (most recent call last):
  File "/home/siena/git/livedoc/livedoc/__init__.py", line 62, in process_element
    expr.evaluate(self.variables, fixtures)
  File "/home/siena/git/livedoc/livedoc/__init__.py", line 197, in evaluate
    self.success = self._operate(fixtures)
  File "/home/siena/git/livedoc/livedoc/__init__.py", line 203, in _operate
    return eval("%s %s %s" % (l, self.operator, r), {}, {})
  File "<string>", line 1, in <module>
NameError: name 'example' is not defined


Context:
	OUT = 
	TEXT = example
	a = example
```

**Comment by frankgerhardt** [comment]
By the way, running livedoc on the examples should be part of the test suite.

**Comment by magmax** [comment]
document_2 is working fine. Maybe you are still using an old version or watching a previously generated file.

I agree: livedoc examples should be run as part of the test suite. The problem here is that there is no way to see if it worked or not.

I've started to work in JUnit reports, so I can check it and write more examples with non-passing examples (such as not meet conditions or exceptions).

Thank you!
